### ISSUE TITLE
Fix the Dockerfile to install chromium/chrome needed by pupeteer package to work 

### ISSUE THREAD

**Issue by GeekyPS** [GeekyPS/Automata#1]
code base should be able to run within a docker container with all its features working

**Comment by dhaneshragu** [comment]
I would like to work on this.

**Comment by GeekyPS** [comment]
assigned

**Comment by dhaneshragu** [comment]
> assigned

@GeekyPS done, pls check

**Comment by GeekyPS** [comment]
<img width="1147" alt="image" src="https://github.com/GeekyPS/Automata/assets/97830682/9b577d1e-dfa7-4d2d-b5aa-149075e0e457">
on my local machine this is the error being thrown , ist it working on your docker image and if so specify its OS

**Comment by dhaneshragu** [comment]
It's 

> <img alt="image" width="1147" src="https://user-images.githubusercontent.com/97830682/272041007-9b577d1e-dfa7-4d2d-b5aa-149075e0e457.png"> on my local machine this is the error being thrown , ist it working on your docker image and if so specify its OS

Yes it's working on mine. My OS is Windows 11

**Comment by dhaneshragu** [comment]
> <img alt="image" width="1147" src="https://user-images.githubusercontent.com/97830682/272041007-9b577d1e-dfa7-4d2d-b5aa-149075e0e457.png"> on my local machine this is the error being thrown , ist it working on your docker image and if so specify its OS

Hey @GeekyPS its working in mine. The OS is Linux of the docker image
<img width="430" alt="image" src="https://github.com/GeekyPS/Automata/assets/95169037/621667db-c309-4ca2-9e21-74b80e15e323">

**Comment by GeekyPS** [comment]
okay , it ran the problem was by default my m1 mac system had a different distro of linux so `docker build --platform linux/amd64 .` worked for me 

Great Work!
