### ISSUE TITLE
Enhance the API to decrease response time while ensuring 100% success rate in form filling

### ISSUE THREAD

**Issue by GeekyPS** [GeekyPS/Automata#3]
Presently , delay of 100 to 600 ms is used multiple times in fillform api , minimize this , also ensuring pupeteer gets enough time to fill fields in resources rsstricted servers

**Comment by Tushar98644** [comment]
> Presently , delay of 100 to 600 ms is used multiple times in fillform api , minimize this , also ensuring pupeteer gets enough time to fill fields in resources rsstricted servers

I would like to work on this ...
