### ISSUE TITLE
Style the landing page with some css animations

### ISSUE THREAD

**Issue by GeekyPS** [GeekyPS/Automata#7]

**Comment by vanshika8750** [comment]
i can do this. please assign it to me

**Comment by GeekyPS** [comment]
sure , but do respond within 2 days

**Comment by praptisharma28** [comment]
Hey @GeekyPS  ,I want to work on this, could you please assign it to me? Thank you!

**Comment by Dhruv127** [comment]
please assign this to me , i have already made a PR #10 with some added animations.
do tell me if  i should make any other changes too..
